config/routes.rb
Rails.application.routes.draw do
  resources :participants
  resources :messages
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	get '/signin', to: 'sessions#new'
	post '/signin', to: 'sessions#create'
	delete '/signout', to: 'sessions#destroy'

	#
	resources :chatboxes do
		resources :messages
	end
	resources :users
	root 'chatboxes#index'
end

app/models/chat_box.rb
class ChatBox < ApplicationRecord

  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  
end

app/models/chatbox.rb
class Chatbox < ApplicationRecord
	has_many :messages
	has_many :participants, dependent: :destroy
	after_create_commit { broadcast_if_public }
	
	validates_uniqueness_of :name
	scope :public_chatboxes, -> { where(is_private: false) }
	# after_create_commit {broadcast_append_to "chatboxes"}




	def broadcast_if_public
		broadcast_append_to "rooms" unless self.is_private
	end

	def self.create_private_room(users, room_name)
		single_chatbox = Chatbox.create(name: chatbox_name, is_private: true)
		users.each do |user|
		Participant.create(user_id: user.id, chatbox_id: single_chatbox.id )
	end
		single_chatbox
	end
end

app/controllers/chatboxes_controller.rb
class ChatboxesController < ApplicationController
	before_action :set_chatbox, only: %i[ show edit update destroy ]

	# GET /chatboxes or /chatboxes.json
	def index
		@current_user = current_user
		redirect_to '/signin' unless @current_user
		@chatboxes = Chatbox.public_chatboxes

		# @single_chatbox = Chatbox.find(params[:id])
		@users = User.all_except(@current_user)
	end

	# GET /chatboxes/1 or /chatboxes/1.json
	def show
		@current_user = current_user
		@single_chatbox = Chatbox.find(params[:id])
		@chatboxes = Chatbox.public_chatboxes
		@users = User.all_except(@current_user)
		@message = Message.new
		@messages = @single_chatbox.messages
		@chatbox = Chatbox.new

	render "index"
	end

	# GET /chatboxes/new
	def new
		@chatbox = Chatbox.new
	end

	# GET /chatboxes/1/edit
	def edit
	end

	# POST /chatboxes or /chatboxes.json
	def create

		@chatbox = Chatbox.new(chatbox_params)

		respond_to do |format|
			if @chatbox.save
				format.html { redirect_to chatbox_url(@chatbox), notice: "Chatbox was successfully created." }
				format.json { render :show, status: :created, location: @chatbox }
			else
				format.html { render :new, status: :unprocessable_entity }
				format.json { render json: @chatbox.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /chatboxes/1 or /chatboxes/1.json
	def update
		respond_to do |format|
			if @chatbox.update(chatbox_params)
				format.html { redirect_to chatbox_url(@chatbox), notice: "Chatbox was successfully updated." }
				format.json { render :show, status: :ok, location: @chatbox }
			else
				format.html { render :edit, status: :unprocessable_entity }
				format.json { render json: @chatbox.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /chatboxes/1 or /chatboxes/1.json
	def destroy
		@chatbox.destroy

		respond_to do |format|
			format.html { redirect_to chatboxes_url, notice: "Chatbox was successfully destroyed." }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_chatbox
			@chatbox = Chatbox.find(params[:id])
		end

		# Only allow a list of trusted parameters through.
		def chatbox_params
			params.permit(:name, :is_private)
		end
end

app/helpers/chatboxes_helper.rb
module ChatboxesHelper
end

app/views/chatboxes/_chatbox.html.erb
<div> <%= link_to chatbox.name, chatbox %> </div>

app/views/chatboxes/_form.html.erb
<%= form_with(model: chatbox) do |form| %>
  <% if chatbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatbox.errors.count, "error") %> prohibited this chatbox from being saved:</h2>

      <ul>
        <% chatbox.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :is_private %>
    <%= form.check_box :is_private %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatboxes/edit.html.erb
<h1>Editing Chatbox</h1>

<%= render 'form', chatbox: @chatbox %>

<%= link_to 'Show', @chatbox %> |
<%= link_to 'Back', chatboxes_path %>

app/views/chatboxes/index.html.erb
	<div class="row float-right left-1"><%= link_to 'Sign Out', signout_path,  :method => :delete %></div>
<div class="container">

<div class="row">
  <div class="col-md-2">
    <h5> Hi <%= @current_user.username %> </h5>
    <h4> Users </h4>
    <div>
      <%= turbo_stream_from "users" %>
      <div id="users">
        <%= render @users %>
      </div>
    </div>
    <h4> ChatBoxes </h4>
    <%= render partial: "layouts/new_chatbox_form" %>
    <div>
      <%= turbo_stream_from "chatboxes" %>
      <div id="chatboxes">
        <%= render @chatboxes %>
      </div>
    </div>
  </div>
  <div class="col-md-10 bg-dark text-light">
    <h4 class="text-center white-text"> <%= @current_user.username || @single_chatbox.name %> </h4>
    <% if @single_chatbox %>
        <%= turbo_stream_from @single_chatbox %>
      <div id="messages">
          <%= render @messages %>
      </div>
      <%= render partial: 'layouts/new_message_form' %>
    <% end %>
  </div>
</div>
</div>

app/views/chatboxes/new.html.erb
<h1>New Chatbox</h1>

<%= render 'form', chatbox: @chatbox %>

<%= link_to 'Back', chatboxes_path %>

app/views/chatboxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chatbox.name %>
</p>

<p>
  <strong>Is private:</strong>
  <%= @chatbox.is_private %>
</p>

<%= link_to 'Edit', edit_chatbox_path(@chatbox) %> |
<%= link_to 'Back', chatboxes_path %>